# Generated by Django 2.1.1 on 2018-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181129_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dayChosen',
            field=models.CharField(max_length=64),
        ),
    ]
